#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-only
# Copyright (C) 2026 ChoralRoot FM-1 contributors (a fork of Felucca)
"""QUAD (firmware/src/eng_quad.c, docs/QUAD.md): the table generator and a reference model of the voice.

  python3 tests/quad_ref.py          # writes firmware/src/quad_tables.h and tests/quad_goldens/*.json

The tables: the 15 harmonic tables (HARM: sine, 7 odd-series steps, 7 all-series steps; 1024 points + the wrap
point, int16, flash), the ratio tables (C / B steps, A steps, the B pair's BR), the value-name lists of the ratio and
offset columns, the base-width filter's one-pole coefficients, the LFO rate constant.

The model: pure Python (no numpy), the same equations as eng_quad.c. The control path (phase increments, the four
envelopes, the LFOs, the level / amplitude ramps, the filter coefficients) is integer, as the firmware's; the signal
path (the operators, feedback, the mix, the SVF, the base-width filter, the amplitude) is float. The goldens: 0.3 s of
two notes (C4 and G4, velocity 100, released at 0.2 s) on eight test patches (one per algorithm) and four presets:
the first 2048 output samples and the RMS of each 10 ms block. tests/cr_quad_test.c renders the same and compares.
Needs build/gen/felucca_tables.h (Felucca's tables: sine, pitch, envelope times, SVF g, tanh).
"""
import json
import math
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TABLES = os.path.join(ROOT, "build", "gen", "felucca_tables.h")
OUT_H = os.path.join(ROOT, "firmware", "src", "quad_tables.h")
GOLD = os.path.join(ROOT, "tests", "quad_goldens")
FS = 44100
CTL = 32
M32 = 0xFFFFFFFF


# ------------------------------------------------------------------ tables
def felucca_table(name):
    src = open(TABLES).read()
    m = re.search(r"\b%s\[\d*\]\s*=\s*\{(.*?)\};" % name, src, re.S)
    if not m:
        sys.exit("quad_ref: %s not in %s (build the generated tables first)" % (name, TABLES))
    return [int(x) for x in re.findall(r"-?\d+", m.group(1))]


SINE = felucca_table("SINE")
PITCH_OCT = felucca_table("PITCH_OCT")
ENV_LIN = felucca_table("ENV_LIN")
ENV_EXP = felucca_table("ENV_EXP")
SVF_G = felucca_table("SVF_G")
TANH_Q15 = felucca_table("TANH_Q15")

# the ratio steps: C and B 0.25 0.5 0.75 then 1..16 (19); A 0.25..16 in 0.25 (64); the B pair: B1 a C/B step, B2 =
# B1 x BR, BR one of six; the pair's index = BR index x 19 + B1 index (B1 cycles through its steps, then BR steps)
RCB = [0.25, 0.5, 0.75] + [float(n) for n in range(1, 17)]
RA = [0.25 * (i + 1) for i in range(64)]
BR = [0.5, 1.0, 1.5, 2.0, 3.0, 4.0]
NRB = len(RCB) * len(BR)
RB_DEF = 1 * len(RCB) + 3               # 1.00 / 1.00
LFO_K = 9739                            # SPEED x MULT x LFO_K a control tick: f = SPEED x MULT / 320 Hz
NHARM = 7


def q16(r):
    return int(round(r * 65536))


def harm_tables():
    """15 tables of 1025 points (the last = the first): 0 sine, 1..7 the odd series up to harmonic 2k + 1 (toward a
    square), 8..14 all harmonics up to 2k + 1 (toward a saw); amplitudes 1 / n, each scaled to a peak of 32767"""
    out = []
    for t in range(2 * NHARM + 1):
        k = 0 if t == 0 else (t if t <= NHARM else t - NHARM)
        odd = t <= NHARM
        hs = [n for n in range(1, 2 * k + 2) if (n % 2 == 1 or not odd)]
        raw = [sum(math.sin(2 * math.pi * n * i / 1024) / n for n in hs) for i in range(1024)]
        fine = [sum(math.sin(2 * math.pi * n * i / 8192) / n for n in hs) for i in range(8192)]
        pk = max(abs(x) for x in fine)
        tab = [int(round(32767 * x / pk)) for x in raw]
        tab = [max(-32767, min(32767, x)) for x in tab]
        out.append(tab + [tab[0]])
    return out


HARM = harm_tables()


def cutoff_hz(v):
    return 30.0 * ((16000 / 30) ** (v / 127))


BW_K = [min(65535, int(round(65536 * (1 - math.exp(-2 * math.pi * cutoff_hz(v) / FS))))) for v in range(128)]


def rtxt(r):
    return "%.2f" % r


def write_header():
    L = ["/* generated by tests/quad_ref.py: do not edit (python3 tests/quad_ref.py) */",
         "/* QUAD (eng_quad.c, docs/QUAD.md): the harmonic tables, the ratio tables, the value names */",
         "#pragma once",
         "#include <stdint.h>",
         "#define QUAD_NRCB %du                /* RATIO C (and B1): 0.25 0.5 0.75 1 2 .. 16 */" % len(RCB),
         "#define QUAD_NRA %du                 /* RATIO A: 0.25 .. 16 in 0.25 */" % len(RA),
         "#define QUAD_NBR %du                  /* the B pair's B2 / B1 */" % len(BR),
         "#define QUAD_NRB %du                /* RATIO B: BR index x QUAD_NRCB + B1 index */" % NRB,
         "#define QUAD_RB_DEF %d               /* 1.00 / 1.00 */" % RB_DEF,
         "#define QUAD_LFO_K %d              /* LFO: SPEED x MULT x QUAD_LFO_K a control tick (f = SPEED x MULT / 320 Hz) */" % LFO_K]

    def arr(name, ctype, vals, per=12):
        L.append("static const %s %s[%d] = {" % (ctype, name, len(vals)))
        for i in range(0, len(vals), per):
            L.append("    " + ", ".join(str(v) for v in vals[i:i + per]) + ",")
        L.append("};")

    def names(name, vals):
        L.append("static const char *const %s[%d] = {" % (name, len(vals) + 1))
        for i in range(0, len(vals), 8):
            L.append("    " + ", ".join('"%s"' % v for v in vals[i:i + 8]) + ",")
        L.append("    0,")
        L.append("};")

    arr("QUAD_RCB_Q16", "int32_t", [q16(r) for r in RCB], 10)
    arr("QUAD_RA_Q16", "int32_t", [q16(r) for r in RA], 10)
    arr("QUAD_BR_Q16", "int32_t", [q16(r) for r in BR], 10)
    L.append("/* the value names (F_INT columns with a 0-terminated name list: value v - min names it) */")
    names("N_QUAD_RCB", [rtxt(r) for r in RCB])
    names("N_QUAD_RA", [rtxt(r) for r in RA])
    names("N_QUAD_RB", ["%s/%s" % (rtxt(RCB[i % len(RCB)]), rtxt(RCB[i % len(RCB)] * BR[i // len(RCB)])) for i in range(NRB)])
    names("N_QUAD_OFS", [("+" if o >= 0 else "-") + "%d.%02d" % (abs(o) // 100, abs(o) % 100) for o in range(-100, 101)])
    L.append("/* the base-width filter: a one-pole's coefficient (Q16) at 30 Hz x (16000 / 30)^(v / 127) (CUTOFF_HZ's scale) */")
    arr("QUAD_BW_K", "uint16_t", BW_K)
    L.append("/* HARM: 0 sine, 1..7 odd harmonics up to 3 5 .. 15, 8..14 all harmonics up to 3 5 .. 15 (1 / n, peak 32767);")
    L.append(" * 1024 points and the first again (no wrap in the interpolation). Flash (XIP): 30.8 KB */")
    L.append("static const int16_t QUAD_HARM[%d][1025] = {" % len(HARM))
    for t in HARM:
        L.append("    {")
        for i in range(0, 1025, 16):
            L.append("        " + ", ".join(str(v) for v in t[i:i + 16]) + ",")
        L.append("    },")
    L.append("};")
    with open(OUT_H, "w") as f:
        f.write("\n".join(L) + "\n")


# ------------------------------------------------------------- the patch
LFO_F = ["SPEED", "MULT", "FADE", "DEST", "WAVE", "PHASE", "TRIG", "DEPTH"]
NAMES = ["ALGO", "RC", "RA", "RB", "HARM", "DTUN", "FDBK", "MIX", "OFSC", "OFSA", "OFSB1", "OFSB2",
         "AATK", "ADEC", "AEND", "ALEV", "BATK", "BDEC", "BEND", "BLEV", "ADLY", "ATRIG", "ARST", "PHRST",
         "BDLY", "BTRIG", "BRST", "VEL", "AKTRK", "BKTRK", "FATK", "FDEC", "FSUS", "FREL", "FREQ", "RESO", "FTYPE",
         "FDEPTH", "FDLY", "FKTRK", "BASE", "WIDTH", "EATK", "EDEC", "ESUS", "EREL", "LEVEL"]
NAMES += ["L%d%s" % (k, f) for k in range(3) for f in LFO_F]
Q = {n: i for i, n in enumerate(NAMES)}
NP = len(NAMES)
assert NP == 71
# (min, max, def), as eng_quad.c's page columns
RNG = {"ALGO": (1, 8, 1), "RC": (0, 18, 3), "RA": (0, 63, 3), "RB": (0, NRB - 1, RB_DEF), "HARM": (-26, 26, 0),
       "DTUN": (0, 127, 0), "FDBK": (0, 127, 0), "MIX": (-63, 63, 0), "OFSC": (-100, 100, 0), "OFSA": (-100, 100, 0),
       "OFSB1": (-100, 100, 0), "OFSB2": (-100, 100, 0), "AATK": (0, 127, 0), "ADEC": (0, 127, 60),
       "AEND": (0, 127, 64), "ALEV": (0, 127, 48), "BATK": (0, 127, 0), "BDEC": (0, 127, 60), "BEND": (0, 127, 0),
       "BLEV": (0, 127, 0), "ADLY": (0, 127, 0), "ATRIG": (0, 1, 1), "ARST": (0, 1, 1), "PHRST": (0, 1, 1),
       "BDLY": (0, 127, 0), "BTRIG": (0, 1, 1), "BRST": (0, 1, 1), "VEL": (0, 127, 64), "AKTRK": (0, 127, 0),
       "BKTRK": (0, 127, 0), "FATK": (0, 127, 0), "FDEC": (0, 127, 64), "FSUS": (0, 127, 0), "FREL": (0, 127, 40),
       "FREQ": (0, 127, 127), "RESO": (0, 127, 0), "FTYPE": (0, 2, 0), "FDEPTH": (-64, 63, 0), "FDLY": (0, 127, 0),
       "FKTRK": (0, 127, 0), "BASE": (0, 127, 0), "WIDTH": (0, 127, 127), "EATK": (0, 127, 0), "EDEC": (0, 127, 64),
       "ESUS": (0, 127, 127), "EREL": (0, 127, 40), "LEVEL": (0, 127, 100)}
for _k in range(3):
    RNG.update({"L%dSPEED" % _k: (-64, 64, 16), "L%dMULT" % _k: (0, 11, 3), "L%dFADE" % _k: (0, 127, 0),
                "L%dDEST" % _k: (0, 12, 0), "L%dWAVE" % _k: (0, 6, 0), "L%dPHASE" % _k: (0, 127, 0),
                "L%dTRIG" % _k: (0, 4, 0), "L%dDEPTH" % _k: (-64, 63, 0)})
FT = {"LP": 0, "HP": 1, "BP": 2}
WAVE = {"TRI": 0, "SINE": 1, "SQR": 2, "SAW": 3, "RAMP": 4, "EXP": 5, "RAND": 6}
TRIG = {"FREE": 0, "TRIG": 1, "HOLD": 2, "ONE": 3, "HALF": 4}
DEST = {"OFF": 0, "HARM": 1, "DTUN": 2, "FDBK": 3, "MIX": 4, "RA": 5, "RB": 6, "FREQ": 7, "RESO": 8, "LEVEL": 9,
        "PAN": 10, "ALEV": 11, "BLEV": 12}


def init_patch():
    return [RNG[n][2] for n in NAMES]


def QRC(q):
    return q - 1 if q <= 4 else q // 4 + 2


def QRB(q, br):
    return br * len(RCB) + QRC(q)


def patch_of(**kw):
    p = init_patch()
    for k, v in kw.items():
        lo, hi, _ = RNG[k]
        p[Q[k]] = max(lo, min(hi, v))
    return p


def syn(al, rc, ra, rb, h, dt, fb, mx):
    return dict(ALGO=al, RC=rc, RA=ra, RB=rb, HARM=h, DTUN=dt, FDBK=fb, MIX=mx)


def env(x, a, d, e, l):
    return {x + "ATK": a, x + "DEC": d, x + "END": e, x + "LEV": l}


def amp(a, d, s, r, l):
    return dict(EATK=a, EDEC=d, ESUS=s, EREL=r, LEVEL=l)


def flt(ty, f, r, dp):
    return dict(FTYPE=FT[ty], FREQ=f, RESO=r, FDEPTH=dp)


def fenv(a, d, s, r):
    return dict(FATK=a, FDEC=d, FSUS=s, FREL=r)


def lfo(k, sp, mu, de, w, dp, tr="FREE"):
    return {"L%dSPEED" % k: sp, "L%dMULT" % k: mu, "L%dDEST" % k: DEST[de], "L%dWAVE" % k: WAVE[w],
            "L%dDEPTH" % k: dp, "L%dTRIG" % k: TRIG[tr]}


def merge(*ds):
    r = {}
    for d in ds:
        r.update(d)
    return r


# four of eng_quad.c's presets (the C test checks these patches against its own)
PRESETS = {
    "EP": patch_of(**merge(syn(2, QRC(4), 3, QRB(56, 1), 0, 10, 0, 0), env("A", 0, 80, 24, 72), env("B", 0, 46, 0, 44),
                           dict(VEL=100, BKTRK=40), amp(0, 96, 40, 62, 72))),
    "BASS": patch_of(**merge(syn(1, QRC(4), 3, QRB(4, 1), 0, 0, 30, 0), env("A", 0, 62, 30, 86), env("B", 0, 50, 0, 40),
                             flt("LP", 92, 10, 20), fenv(0, 60, 0, 40), amp(0, 80, 100, 30, 110))),
    "GLASS PAD": patch_of(**merge(syn(7, QRC(4), 7, QRB(16, 1), 8, 40, 0, 0), env("A", 70, 90, 100, 60),
                                  env("B", 80, 96, 60, 40), amp(70, 90, 120, 100, 92), lfo(0, 8, 3, "HARM", "SINE", 30))),
    "WOBBLE": patch_of(**merge(syn(1, QRC(4), 3, QRB(4, 1), 0, 0, 20, 0), env("A", 0, 64, 127, 60),
                               env("B", 0, 60, 40, 30), flt("LP", 70, 60, 0), amp(0, 80, 110, 40, 115),
                               lfo(0, 32, 4, "ALEV", "TRI", 50, "TRIG"), lfo(1, 32, 4, "FREQ", "TRI", 40, "TRIG"))),
}


def algo_patch(al):
    """a test patch for algorithm al: every part of the voice moving (both envelopes, HARM, detune, feedback, the
    filter and its envelope, the base-width filter, an LFO on MIX)"""
    return patch_of(**merge(syn(al, QRC(4), 7, QRB(4, 3), 8 if al % 2 else -10, 30, 40, 20),
                            env("A", 0, 60, 40, 80), env("B", 5, 70, 30, 70), flt("LP", 100, 30, 20),
                            fenv(0, 60, 40, 40), dict(BASE=10, WIDTH=100, OFSB2=3), amp(2, 70, 100, 40, 100),
                            lfo(0, 20, 4, "MIX", "TRI", 30, "TRIG")))


# --------------------------------------------------------------- the model
def mulq15(a, b):
    return (a * b) >> 15


def mulq16(a, k):
    return ((a >> 16) * k) + (((a & 0xFFFF) * k) >> 16)


def clamp(v, lo, hi):
    return lo if v < lo else hi if v > hi else v


def cdiv(a, b):
    q = abs(a) // abs(b)
    return q if (a >= 0) == (b > 0) else -q


def pitch_inc(p):
    i = p + 64
    o = (i * 21846) >> 22
    return PITCH_OCT[i - o * 192] >> (10 - o)


def sine_int(ph):
    i = ph >> 22
    a, b = SINE[i], SINE[(i + 1) & 1023]
    return a + (((b - a) * ((ph >> 7) & 0x7FFF)) >> 15)


def osc_tri(ph):
    s = (ph & M32) >> 15
    return s - 32768 if s < 65536 else 98303 - s


def xs(s):
    s &= M32
    s = s if s else 0x6C8E9CF5
    s ^= (s << 13) & M32
    s ^= s >> 17
    s ^= (s << 5) & M32
    return s


def tab_f(t, ph):
    """table t at the (float) phase ph, linearly interpolated (the float side of quad_tab / sine_i)"""
    x = (ph % 4294967296.0) / 4194304.0
    i = int(x)
    if i > 1023:
        i = 1023
    f = x - i
    a = t[i]
    return a + (t[i + 1] - a) * f


def softclip_f(x):
    a = abs(x)
    i = int(a) >> 8
    if i >= 256:
        y = TANH_Q15[256]
    else:
        y = TANH_Q15[i] + (TANH_Q15[i + 1] - TANH_Q15[i]) * (a - 256 * i) / 256.0
    return -y if x < 0 else y


def soft_knee_f(y, k):
    a = abs(y)
    if a <= k:
        return y
    a = k + softclip_f((a - k) * 2) / 2.0
    return -a if y < 0 else a


def lfo_inc(p, k):
    mu = p[Q["L%dMULT" % k]]
    return p[Q["L%dSPEED" % k]] * (1 << (mu if mu < 12 else 0)) * LFO_K


def lfo_wave(w, ph, r):
    ph &= M32
    if w == 1:
        return sine_int(ph)
    if w == 2:
        return 32767 if ph < 0x80000000 else -32767
    if w == 3:
        return (((ph + 0x80000000) & M32) >> 16) - 32768
    if w == 4:
        return 32767 - (ph >> 17)
    if w == 5:
        u = 32767 - (ph >> 17)
        u = (u * u) >> 15
        return (u * u) >> 15
    if w == 6:
        return r
    return osc_tri((ph + 0x40000000) & M32)


def tsvf_coef_k(cut, k):
    cut = clamp(cut, 0, 127 << 8)
    i = cut >> 8
    g = SVF_G[i]
    if i < 127:
        g += ((SVF_G[i + 1] - g) * (cut & 255)) >> 8
    den = 4096 + ((g * (g + k)) >> 12)
    a1 = (4096 << 13) // den
    a2 = (a1 * g) >> 12
    a3 = (a2 * g) >> 12
    return a1, a2, a3


class Part:
    def __init__(self, p):
        self.p = p
        self.lph = [0, 0, 0]
        self.lrnd = [0, 0, 0]

    def block(self):
        for k in range(3):
            old = self.lph[k]
            inc = lfo_inc(self.p, k)
            self.lph[k] = (old + inc) & M32
            if (inc > 0 and self.lph[k] < old) or (inc < 0 and self.lph[k] > old):
                self.lrnd[k] = xs(self.lrnd[k] + k)


class Voice:
    def __init__(self, part, idx):
        self.part = part
        self.idx = idx
        self.ph = [0.0] * 4
        self.fb1 = self.fb2 = 0.0
        self.env = [0] * 4
        self.dly = [0] * 4
        self.stage = [0] * 4
        self.lv = [0, 0]
        self.amp = 0
        self.f1 = self.f2 = 0.0
        self.bh = self.bl = 0.0
        self.lph = [0] * 3
        self.lrnd = [0] * 3
        self.ltr = [0] * 3
        self.lstop = 0
        self.ticks = 0
        self.live = 0
        self.gate = 0
        self.active = 0
        self.note = 60
        self.vel = 100
        self.env_out = 0
        self.venv = 0

    def env_start(self, k, d, reset):
        if reset:
            self.env[k] = 0
        self.dly[k] = 0
        self.stage[k] = 1 if d else 2

    def note_on(self, note, vel):
        p = self.part.p
        sounding = self.active
        self.note, self.vel = note, vel
        self.gate = self.active = 1
        if not sounding:
            self.venv = self.env_out = 0
        fresh = (not self.venv and not self.env_out) or not self.live
        if fresh:
            self.ph = [0.0] * 4
            self.env = [0] * 4
            self.fb1 = self.fb2 = 0.0
            self.lv = [0, 0]
            self.amp = 0
            self.f1 = self.f2 = 0.0
            self.bh = self.bl = 0.0
            self.env_start(0, p[Q["ADLY"]], 1)
            self.env_start(1, p[Q["BDLY"]], 1)
        else:
            if p[Q["PHRST"]]:
                self.ph = [0.0] * 4
                self.fb1 = self.fb2 = 0.0
            if p[Q["ATRIG"]]:
                self.env_start(0, p[Q["ADLY"]], p[Q["ARST"]])
            if p[Q["BTRIG"]]:
                self.env_start(1, p[Q["BDLY"]], p[Q["BRST"]])
        self.env_start(2, p[Q["FDLY"]], fresh)
        self.env_start(3, 0, fresh)
        for k in range(3):
            tm = p[Q["L%dTRIG" % k]]
            self.ltr[k] = 0
            self.lstop &= ~(1 << k)
            self.lrnd[k] = xs(self.lrnd[k] + 0x9E3779B9 * (k + 1) + self.idx)
            if tm == 2:
                self.lph[k] = (self.part.lph[k] + (p[Q["L%dPHASE" % k]] << 25)) & M32
                self.lrnd[k] = self.part.lrnd[k]
            else:
                self.lph[k] = p[Q["L%dPHASE" % k]] << 25
        self.ticks = 0
        self.live = 1

    def env_tick(self, k, atk, dec, sus, rel, dly, gate, adsr):
        x = self.env[k]
        if adsr and not gate and self.stage[k] and self.stage[k] < 4:
            self.stage[k] = 4
        st = self.stage[k]
        if st == 1:
            self.dly[k] += ENV_LIN[dly & 127]
            if self.dly[k] >= (1 << 24):
                self.stage[k] = 2
        elif st == 2:
            x += ENV_LIN[atk & 127]
            if x >= (1 << 24):
                x = 1 << 24
                self.stage[k] = 3
        elif st == 3:
            x += mulq16(sus - x, ENV_EXP[dec & 127])
        elif st == 4:
            x -= mulq16(x, ENV_EXP[rel & 127])
            if x < (1 << 12):
                x = 0
                self.stage[k] = 0
        else:
            x = 0
        self.env[k] = x
        return x >> 9

    def done(self):
        if not self.live or not self.stage[3]:
            self.live = 0
            return True
        return False

    def render(self, out, pitch16, inc_base, latest):
        p = self.part.p
        g = lambda n: p[Q[n]]
        eA = self.env_tick(0, g("AATK"), g("ADEC"), g("AEND") << 17, 0, g("ADLY"), 1, 0)
        eB = self.env_tick(1, g("BATK"), g("BDEC"), g("BEND") << 17, 0, g("BDLY"), 1, 0)
        eF = self.env_tick(2, g("FATK"), g("FDEC"), g("FSUS") << 17, g("FREL"), g("FDLY"), self.gate, 1)
        eE = self.env_tick(3, g("EATK"), g("EDEC"), g("ESUS") << 17, g("EREL"), 0, self.gate, 1)
        dst = [0] * 13
        for k in range(3):
            d, tm = g("L%dDEST" % k), g("L%dTRIG" % k)
            inc0 = lfo_inc(p, k)
            if tm == 0:
                ph = (self.part.lph[k] + (g("L%dPHASE" % k) << 25)) & M32
                rv = self.part.lrnd[k]
            else:
                ph = self.lph[k]
                rv = self.lrnd[k]
                if tm != 2 and not (self.lstop >> k) & 1:
                    old = ph
                    st = abs(inc0) >> 1
                    if tm != 1:
                        lim = 0x80000000 if tm == 3 else 0x40000000
                        if self.ltr[k] + st >= lim:
                            st = lim - self.ltr[k]
                            self.lstop |= 1 << k
                        self.ltr[k] += st
                    self.lph[k] = (old + (-(st << 1) if inc0 < 0 else st << 1)) & M32
                    if (inc0 > 0 and self.lph[k] < old) or (inc0 < 0 and self.lph[k] > old):
                        self.lrnd[k] = xs(self.lrnd[k] + k)
            if not d or d >= 13 or not g("L%dDEPTH" % k):
                continue
            w = lfo_wave(g("L%dWAVE" % k), ph, (rv >> 16) - 32768)
            w = (w * g("L%dDEPTH" % k)) >> 6
            fd = g("L%dFADE" % k)
            f = self.ticks * (ENV_LIN[fd] >> 9) if fd else 32767
            if f < 32767:
                w = (w * f) >> 15
            dst[d] += w
        if self.ticks < 0xFFFF:
            self.ticks += 1
        alg = clamp(g("ALGO"), 1, 8)
        dt = clamp(g("DTUN") + ((dst[2] * 127) >> 15), 0, 127)
        ra = clamp(g("RA") + ((dst[5] * 32) >> 15), 0, 63)
        rbi = clamp(g("RB"), 0, NRB - 1)
        br = rbi // 19
        rb1i = clamp(rbi % 19 + ((dst[6] * 18) >> 15), 0, 18)

        def ratio(r, o):
            r += cdiv(o * 65536, 100)
            return 0 if r < 0 else r

        def opinc(r, det):
            qq = (r * (65536 + det)) >> 16
            return (inc_base * qq >> 16) & M32

        rc = ratio(q16(RCB[clamp(g("RC"), 0, 18)]), g("OFSC"))
        rA = ratio(q16(RA[ra]), g("OFSA"))
        rB1 = ratio(q16(RCB[rb1i]), g("OFSB1"))
        rB2 = ratio((q16(RCB[rb1i]) * q16(BR[br])) >> 16, g("OFSB2"))
        db, da = (dt * 15) >> 1, (dt * 15) >> 3
        inc = [opinc(rc, 0), opinc(rA, da), opinc(rB1, -db), opinc(rB2, db)]
        harm = clamp(g("HARM") + ((dst[1] * 26) >> 15), -26, 26)
        hm = harm != 0
        hf = 0
        ha = hb = HARM[0]
        if hm:
            h = abs(harm)
            q = h * 7 * 32768 // 26
            t0 = q >> 15
            t1 = t0 + 1 if t0 < 7 else 7
            hf = q & 32767 if t1 > t0 else 0
            ha = HARM[(7 + t0 if harm < 0 else t0) if t0 else 0]
            hb = HARM[7 + t1 if harm < 0 else t1]
        hff = hf / 32768.0
        fdbk = clamp(g("FDBK") + ((dst[3] * 127) >> 15), 0, 127)
        fbq = fdbk * fdbk * 2
        mix = clamp(g("MIX") + ((dst[4] * 126) >> 15), -63, 63)
        gx, gy = (63 - mix) * 260, (63 + mix) * 260
        vel = self.vel
        velf = 32767 - ((g("VEL") * (127 - vel) * 2080) >> 10)
        tl = [0, 0]
        for j in range(2):
            l = clamp(g("BLEV" if j else "ALEV") + (((dst[12] if j else dst[11]) * 127) >> 15), 0, 127)
            kt = g("BKTRK" if j else "AKTRK")
            l = mulq15(l * l * 2, velf)
            if kt:
                gg = clamp(32768 + (((pitch16 - 960) * kt * 43) >> 7), 0, 65535)
                l = clamp((l * gg) >> 15, 0, 32767)
            tl[j] = mulq15(eB if j else eA, l)
        la, lb = self.lv[0] << 16, self.lv[1] << 16
        dla, dlb = ((tl[0] << 16) - la) >> 5, ((tl[1] << 16) - lb) >> 5
        cut = (g("FREQ") << 8) + ((eF * g("FDEPTH")) >> 6) + (((pitch16 - 960) * g("FKTRK") * 150) >> 10) + \
            ((dst[7] * 127) >> 7)
        reso = clamp(g("RESO") + ((dst[8] * 127) >> 15), 0, 127)
        fty = g("FTYPE")
        svf = not (fty == 0 and cut >= (127 << 8) and not reso)
        kd = 8192 - reso * 60
        a1 = a2 = a3 = 0
        if svf:
            a1, a2, a3 = tsvf_coef_k(cut, kd)
        hpk = BW_K[g("BASE")] / 65536.0 if g("BASE") else 0.0
        lpk = BW_K[g("BASE") + g("WIDTH")] / 65536.0 if g("BASE") + g("WIDTH") < 127 else 0.0
        lv = clamp(g("LEVEL") + ((dst[9] * 127) >> 15), 0, 127)
        A1 = mulq15(mulq15(eE, 32767 - (127 - vel) * 129), lv * lv * 2)
        A1 = mulq15(A1, 32767)
        A0 = self.amp
        dA = (A1 - A0) >> 5
        a = A0
        if latest:
            self.part.pan = clamp((dst[10] * 64) >> 15, -64, 63)
        p0, p1, p2, p3 = self.ph
        fb1, fb2 = self.fb1, self.fb2
        ic1, ic2, bh, bl = self.f1, self.f2, self.bh, self.bl
        S = SINE
        W = lambda ph: tab_f(S, ph)
        if hm:
            CW = lambda ph: tab_f(ha, ph) + ((tab_f(hb, ph) - tab_f(ha, ph)) * hff if hf else 0.0)
        else:
            CW = W
        K = 262144.0     # a modulator's output (Q15) -> phase: << 18
        for i in range(CTL):
            la += dla
            lb += dlb
            LA = (la >> 16) / 32768.0
            LB = (lb >> 16) / 32768.0
            FB = (fb1 + fb2) * fbq * 2.0
            if alg == 1:
                yf = W(p3 + FB)
                ob2 = yf * LB
                ob1 = W(p2 + ob2 * K) * LB
                oa = W(p1 + ob1 * K) * LA
                X = Y = CW(p0 + oa * K)
            elif alg == 2:
                yf = W(p3 + FB)
                ob2 = yf * LB
                ob1 = W(p2 + ob2 * K) * LB
                oa = W(p1) * LA
                X = Y = CW(p0 + oa * K + ob1 * K)
            elif alg == 3:
                yf = W(p3 + FB)
                ob2 = yf * LB
                ob1 = W(p2) * LB
                oa = W(p1 + ob1 * K + ob2 * K) * LA
                X = Y = CW(p0 + oa * K)
            elif alg == 4:
                yf = W(p3 + FB)
                ob2 = yf * LB
                oa = W(p1) * LA
                X = CW(p0 + oa * K)
                Y = CW(p2 + ob2 * K) * LB
            elif alg == 5:
                ob1 = W(p2) * LB
                oa = W(p1 + ob1 * K) * LA
                X = CW(p0 + oa * K)
                yf = CW(p3 + FB)
                Y = yf * LB
            elif alg == 6:
                yf = W(p3 + FB)
                ob2 = yf * LB
                oa = W(p1) * LA
                X = CW(p0 + oa * K)
                Y = CW(p2 + oa * K + ob2 * K) * LB
            elif alg == 7:
                yf = CW(p1 + FB)
                X = CW(p0) + yf * LA
                ob2 = W(p3) * LB
                Y = CW(p2 + ob2 * K) * LB
            else:
                yf = CW(p3 + FB)
                X = CW(p0) + CW(p1) * LA
                Y = CW(p2) * LB + yf * LB
            fb2, fb1 = fb1, yf
            p0 += inc[0]
            p1 += inc[1]
            p2 += inc[2]
            p3 += inc[3]
            x = (X * gx + Y * gy) / 32768.0 / 2.0
            if svf:
                v3 = x - ic2
                v1 = (a1 * ic1 + a2 * v3) / 8192.0
                v2 = ic2 + (a2 * ic1 + a3 * v3) / 8192.0
                ic1 = clamp(2 * v1 - ic1, -150000, 150000)
                ic2 = clamp(2 * v2 - ic2, -150000, 150000)
                y = kd * v1 / 4096.0 if fty == 2 else x - kd * v1 / 4096.0 - v2 if fty == 1 else v2
                y = soft_knee_f(clamp(y, -200000, 200000), 16000)
            else:
                y = x
            if hpk:
                bh += (y - bh) * hpk
                y -= bh
            if lpk:
                bl += (y - bl) * lpk
                y = bl
            y = clamp(y, -65535, 65535)
            a += dA
            out[i] += y * a / 32768.0 * 6000 / 2048.0
        self.ph = [p0 % 4294967296.0, p1 % 4294967296.0, p2 % 4294967296.0, p3 % 4294967296.0]
        self.fb1, self.fb2 = fb1, fb2
        self.f1, self.f2, self.bh, self.bl = ic1, ic2, bh, bl
        self.lv = [tl[0], tl[1]]
        self.amp = A1


def render(patch, notes=(60, 67), vel=100, secs=0.3, rel=0.2):
    part = Part(patch)
    part.pan = 0
    vs = [Voice(part, i) for i in range(len(notes))]
    for v, n in zip(vs, notes):
        v.note_on(n, vel)
    nt = int(secs * FS / CTL)
    out_all = []
    for t in range(nt):
        if t == int(rel * FS / CTL):
            for v in vs:
                v.gate = 0
        part.block()
        out = [0.0] * CTL
        for i, v in enumerate(vs):
            if not v.active:
                continue
            if v.done():
                v.active = v.gate = 0
                v.venv = v.env_out = 0
                continue
            v.venv = 1 << 24
            v.env_out = 32767
            v.render(out, v.note * 16, pitch_inc(v.note * 16), i == len(vs) - 1)
        out_all += out
    return out_all


def golden(name, patch):
    out = render(patch)
    n = len(out)
    rms = []
    for b in range(0, n - 440, 441):
        blk = out[b:b + 441]
        rms.append(round(math.sqrt(sum(x * x for x in blk) / len(blk)), 3))
    g = {"name": name, "patch": patch, "notes": [60, 67], "vel": 100, "secs": 0.3, "release": 0.2, "n": n,
         "first": [int(round(x)) for x in out[:2048]], "rms": rms}
    fn = os.path.join(GOLD, re.sub(r"[^a-z0-9]+", "_", name.lower()) + ".json")
    with open(fn, "w") as f:
        json.dump(g, f, separators=(",", ":"))
    return fn, max(abs(x) for x in out)


def main():
    write_header()
    print("quad_ref: wrote", os.path.relpath(OUT_H, ROOT))
    os.makedirs(GOLD, exist_ok=True)
    jobs = [("algo%d" % a, algo_patch(a)) for a in range(1, 9)] + list(PRESETS.items())
    for name, p in jobs:
        fn, pk = golden(name, p)
        print("quad_ref: %-28s peak %7.0f" % (os.path.relpath(fn, ROOT), pk))


if __name__ == "__main__":
    main()
